### ISSUE TITLE
ResultT

### ISSUE THREAD

**Issue by gocandra** [harvic3/nodetskeleton#5]
I have the following problem using ResultT
`import { BaseUseCase, IResultT, ResultT } from "./base/BaseUseCase"
import { IPatientRepository, IPatient } from "@umahealth/repositories-module"

export class FindPatientUseCase extends BaseUseCase {
  constructor(private readonly PatientRepository: IPatientRepository) {
    super()
  }
  async execute(uid: string, patient: IPatient): Promise<IResultT<IPatient>> {
    const result = new ResultT()
    const patientExists: IPatient = await this.PatientRepository.getByUid(uid)
    result.setData(patientExists, 200)
    return result
  }
}`

it says 
`Type 'Result<unknown>' is not assignable to type 'IResult<IPatient>'.
  Types of property 'data' are incompatible.
    Type 'unknown' is not assignable to type 'string | IPatient'.
      Type 'unknown' is not assignable to type 'IPatient'`
      
 I'm failling to understand how to properly use this library. Could you please give me some guidance?

**Comment by gocandra** [comment]
I've just solved it... ajjajajjaajaja sry to bother
just for anyone else looking for this, you declare result like so.
 const result = new ResultT<IPatient>()

**Comment by harvic3** [comment]
Hi @gocandra result can be use with type ResultT (IResultT) o without type Result (IResult)
With type
const result = new RestultT<YourType>();

Without type
const result = new Result();

I hope this gives you more clarity about the use of this package.

**Comment by harvic3** [comment]
> I have the following problem using ResultT
> `import { BaseUseCase, IResultT, ResultT } from "./base/BaseUseCase"
> import { IPatientRepository, IPatient } from "@umahealth/repositories-module"
> 
> export class FindPatientUseCase extends BaseUseCase {
> constructor(private readonly PatientRepository: IPatientRepository) {
> super()
> }
> async execute(uid: string, patient: IPatient): Promise<IResultT> {
> const result = new ResultT()
> const patientExists: IPatient = await this.PatientRepository.getByUid(uid)
> result.setData(patientExists, 200)
> return result
> }
> }`
> 
> it says
> `Type 'Result<unknown>' is not assignable to type 'IResult<IPatient>'. Types of property 'data' are incompatible. Type 'unknown' is not assignable to type 'string | IPatient'. Type 'unknown' is not assignable to type 'IPatient'`
> 
> I'm failling to understand how to properly use this library. Could you please give me some guidance?

@gocandra  in this line, you can use the statusCode using Clean Code: 
```ts
result.setData(patientExists, this.applicationStatus.SUCCESS,)
```

If you need create more aplication status codes, so you can map this status codes into the file StatusMapping in path:
src/adapters/controllers/base/httpResponse/

**Comment by gocandra** [comment]
thanks! yeah, everything just fell into place afterwards. I was struggling at first with incorporating the whole framework into my head, but I fell that I'm now able to extract the most value out of this template. This is a very nice project, congrats!!

**Comment by harvic3** [comment]
Thanks @gocandra, but don't forget to leave your star. It's a way to move the project forward and a form of support. ^^
